repos:
-   repo: https://github.com/ambv/black
    rev: 24.3.0
    hooks:
    - id: black
      language_version: python3.10
-   repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: pytest
      language: system
      types: [python]
      pass_filenames: false
      always_run: true